// This file is auto-generated by @hey-api/openapi-ts

export const AccountCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            title: 'Name'
        },
        type: {
            '$ref': '#/components/schemas/AccountType'
        },
        institution: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Institution'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    required: ['name', 'type'],
    title: 'AccountCreate'
} as const;

export const AccountPublicSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            title: 'Name'
        },
        type: {
            '$ref': '#/components/schemas/AccountType'
        },
        institution: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Institution'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['name', 'type', 'id', 'created_at'],
    title: 'AccountPublic'
} as const;

export const AccountSpendingSchema = {
    properties: {
        account_id: {
            type: 'string',
            format: 'uuid',
            title: 'Account Id'
        },
        account_name: {
            type: 'string',
            title: 'Account Name'
        },
        account_type: {
            type: 'string',
            title: 'Account Type'
        },
        total_expense_cents: {
            type: 'integer',
            title: 'Total Expense Cents'
        },
        total_income_cents: {
            type: 'integer',
            title: 'Total Income Cents'
        },
        net_cents: {
            type: 'integer',
            title: 'Net Cents'
        },
        transaction_count: {
            type: 'integer',
            title: 'Transaction Count'
        }
    },
    type: 'object',
    required: ['account_id', 'account_name', 'account_type', 'total_expense_cents', 'total_income_cents', 'net_cents', 'transaction_count'],
    title: 'AccountSpending',
    description: 'Spending summary for a single account.'
} as const;

export const AccountSummaryResponseSchema = {
    properties: {
        accounts: {
            items: {
                '$ref': '#/components/schemas/AccountSpending'
            },
            type: 'array',
            title: 'Accounts'
        },
        consolidated_expense_cents: {
            type: 'integer',
            title: 'Consolidated Expense Cents'
        },
        consolidated_income_cents: {
            type: 'integer',
            title: 'Consolidated Income Cents'
        },
        consolidated_net_cents: {
            type: 'integer',
            title: 'Consolidated Net Cents'
        },
        total_transaction_count: {
            type: 'integer',
            title: 'Total Transaction Count'
        },
        period_start: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Period Start'
        },
        period_end: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Period End'
        }
    },
    type: 'object',
    required: ['accounts', 'consolidated_expense_cents', 'consolidated_income_cents', 'consolidated_net_cents', 'total_transaction_count', 'period_start', 'period_end'],
    title: 'AccountSummaryResponse',
    description: 'Response for account summary analysis.'
} as const;

export const AccountTypeSchema = {
    type: 'string',
    enum: ['credit_card', 'chequing', 'savings', 'investment', 'other'],
    title: 'AccountType'
} as const;

export const AccountUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        type: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/AccountType'
                },
                {
                    type: 'null'
                }
            ]
        },
        institution: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Institution'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    title: 'AccountUpdate'
} as const;

export const AccountsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/AccountPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'AccountsPublic'
} as const;

export const Body_imports_upload_pdfSchema = {
    properties: {
        file: {
            type: 'string',
            format: 'binary',
            title: 'File'
        }
    },
    type: 'object',
    required: ['file'],
    title: 'Body_imports-upload_pdf'
} as const;

export const Body_login_login_access_tokenSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: 'password'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_login-login_access_token'
} as const;

export const CategoriesPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/CategoryPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'CategoriesPublic'
} as const;

export const CategoryCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            title: 'Name'
        }
    },
    type: 'object',
    required: ['name'],
    title: 'CategoryCreate'
} as const;

export const CategoryPublicSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            title: 'Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['name', 'id', 'created_at'],
    title: 'CategoryPublic'
} as const;

export const CategorySpendingSchema = {
    properties: {
        category_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Category Id'
        },
        category_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Category Name'
        },
        total_cents: {
            type: 'integer',
            title: 'Total Cents'
        },
        percentage: {
            type: 'number',
            title: 'Percentage'
        },
        transaction_count: {
            type: 'integer',
            title: 'Transaction Count'
        }
    },
    type: 'object',
    required: ['category_id', 'category_name', 'total_cents', 'percentage', 'transaction_count'],
    title: 'CategorySpending',
    description: 'Spending data for a single category.'
} as const;

export const CategoryUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        }
    },
    type: 'object',
    title: 'CategoryUpdate'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const ImportPreviewPublicSchema = {
    properties: {
        import_id: {
            type: 'string',
            format: 'uuid',
            title: 'Import Id'
        },
        file_name: {
            type: 'string',
            title: 'File Name'
        },
        statement_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Statement Date'
        },
        statement_total_cents: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Statement Total Cents'
        },
        calculated_total_cents: {
            type: 'integer',
            title: 'Calculated Total Cents'
        },
        totals_match: {
            type: 'boolean',
            title: 'Totals Match'
        },
        transactions: {
            items: {
                '$ref': '#/components/schemas/TransactionPreview'
            },
            type: 'array',
            title: 'Transactions'
        },
        warnings: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Warnings'
        }
    },
    type: 'object',
    required: ['import_id', 'file_name', 'statement_date', 'statement_total_cents', 'calculated_total_cents', 'totals_match', 'transactions', 'warnings'],
    title: 'ImportPreviewPublic',
    description: 'Preview response after PDF extraction.'
} as const;

export const ImportResultPublicSchema = {
    properties: {
        import_session_id: {
            type: 'string',
            format: 'uuid',
            title: 'Import Session Id'
        },
        transactions_imported: {
            type: 'integer',
            title: 'Transactions Imported'
        },
        success: {
            type: 'boolean',
            title: 'Success'
        }
    },
    type: 'object',
    required: ['import_session_id', 'transactions_imported', 'success'],
    title: 'ImportResultPublic',
    description: 'Result after confirming import.'
} as const;

export const ImportSessionPublicSchema = {
    properties: {
        file_name: {
            type: 'string',
            maxLength: 255,
            title: 'File Name'
        },
        account_id: {
            type: 'string',
            format: 'uuid',
            title: 'Account Id'
        },
        status: {
            '$ref': '#/components/schemas/ImportStatus',
            default: 'pending'
        },
        transaction_count: {
            type: 'integer',
            title: 'Transaction Count',
            default: 0
        },
        statement_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Statement Date'
        },
        statement_total_cents: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Statement Total Cents'
        },
        calculated_total_cents: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Calculated Total Cents'
        },
        error_message: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Error Message'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        completed_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Completed At'
        }
    },
    type: 'object',
    required: ['file_name', 'account_id', 'id', 'created_at', 'completed_at'],
    title: 'ImportSessionPublic'
} as const;

export const ImportSessionsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ImportSessionPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ImportSessionsPublic'
} as const;

export const ImportStatusSchema = {
    type: 'string',
    enum: ['pending', 'completed', 'rejected', 'failed'],
    title: 'ImportStatus'
} as const;

export const ItemCreateSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    required: ['title'],
    title: 'ItemCreate'
} as const;

export const ItemPublicSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        }
    },
    type: 'object',
    required: ['title', 'id', 'owner_id'],
    title: 'ItemPublic'
} as const;

export const ItemUpdateSchema = {
    properties: {
        title: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    title: 'ItemUpdate'
} as const;

export const ItemsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ItemPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ItemsPublic'
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message'
} as const;

export const MonthlySpendingSchema = {
    properties: {
        year: {
            type: 'integer',
            title: 'Year'
        },
        month: {
            type: 'integer',
            title: 'Month'
        },
        total_cents: {
            type: 'integer',
            title: 'Total Cents'
        },
        transaction_count: {
            type: 'integer',
            title: 'Transaction Count'
        }
    },
    type: 'object',
    required: ['year', 'month', 'total_cents', 'transaction_count'],
    title: 'MonthlySpending',
    description: 'Spending data for a single month.'
} as const;

export const NewPasswordSchema = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['token', 'new_password'],
    title: 'NewPassword'
} as const;

export const PrivateUserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            title: 'Email'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        full_name: {
            type: 'string',
            title: 'Full Name'
        },
        is_verified: {
            type: 'boolean',
            title: 'Is Verified',
            default: false
        }
    },
    type: 'object',
    required: ['email', 'password', 'full_name'],
    title: 'PrivateUserCreate'
} as const;

export const SpendingByCategoryResponseSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/CategorySpending'
            },
            type: 'array',
            title: 'Data'
        },
        total_spending_cents: {
            type: 'integer',
            title: 'Total Spending Cents'
        },
        period_start: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Period Start'
        },
        period_end: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Period End'
        }
    },
    type: 'object',
    required: ['data', 'total_spending_cents', 'period_start', 'period_end'],
    title: 'SpendingByCategoryResponse',
    description: 'Response for spending by category analysis.'
} as const;

export const SpendingTrendsResponseSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/MonthlySpending'
            },
            type: 'array',
            title: 'Data'
        },
        total_spending_cents: {
            type: 'integer',
            title: 'Total Spending Cents'
        },
        period_start: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Period Start'
        },
        period_end: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Period End'
        }
    },
    type: 'object',
    required: ['data', 'total_spending_cents', 'period_start', 'period_end'],
    title: 'SpendingTrendsResponse',
    description: 'Response for monthly spending trends.'
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: ['access_token'],
    title: 'Token'
} as const;

export const TransactionCreateSchema = {
    properties: {
        date_transaction: {
            type: 'string',
            format: 'date',
            title: 'Date Transaction'
        },
        date_inscription: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Date Inscription'
        },
        description: {
            type: 'string',
            maxLength: 500,
            title: 'Description'
        },
        amount_cents: {
            type: 'integer',
            exclusiveMinimum: 0,
            title: 'Amount Cents'
        },
        type: {
            '$ref': '#/components/schemas/TransactionType'
        },
        note: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Note'
        },
        source_file: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Source File'
        },
        statement_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Statement Date'
        },
        account_id: {
            type: 'string',
            format: 'uuid',
            title: 'Account Id'
        },
        category_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Category Id'
        }
    },
    type: 'object',
    required: ['date_transaction', 'description', 'amount_cents', 'type', 'account_id'],
    title: 'TransactionCreate'
} as const;

export const TransactionPreviewSchema = {
    properties: {
        date_transaction: {
            type: 'string',
            format: 'date',
            title: 'Date Transaction'
        },
        description: {
            type: 'string',
            title: 'Description'
        },
        amount_cents: {
            type: 'integer',
            title: 'Amount Cents'
        },
        type: {
            '$ref': '#/components/schemas/TransactionType'
        }
    },
    type: 'object',
    required: ['date_transaction', 'description', 'amount_cents', 'type'],
    title: 'TransactionPreview',
    description: 'Single transaction in import preview.'
} as const;

export const TransactionPublicSchema = {
    properties: {
        date_transaction: {
            type: 'string',
            format: 'date',
            title: 'Date Transaction'
        },
        date_inscription: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Date Inscription'
        },
        description: {
            type: 'string',
            maxLength: 500,
            title: 'Description'
        },
        amount_cents: {
            type: 'integer',
            exclusiveMinimum: 0,
            title: 'Amount Cents'
        },
        type: {
            '$ref': '#/components/schemas/TransactionType'
        },
        note: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Note'
        },
        source_file: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Source File'
        },
        statement_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Statement Date'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        account_id: {
            type: 'string',
            format: 'uuid',
            title: 'Account Id'
        },
        category_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Category Id'
        },
        status: {
            '$ref': '#/components/schemas/TransactionStatus'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        account: {
            '$ref': '#/components/schemas/AccountPublic'
        },
        category: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/CategoryPublic'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    type: 'object',
    required: ['date_transaction', 'description', 'amount_cents', 'type', 'id', 'account_id', 'category_id', 'status', 'created_at', 'account', 'category'],
    title: 'TransactionPublic'
} as const;

export const TransactionStatusSchema = {
    type: 'string',
    enum: ['auto', 'confirmed', 'manual'],
    title: 'TransactionStatus'
} as const;

export const TransactionTypeSchema = {
    type: 'string',
    enum: ['expense', 'income', 'transfer'],
    title: 'TransactionType'
} as const;

export const TransactionUpdateSchema = {
    properties: {
        date_transaction: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Date Transaction'
        },
        date_inscription: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Date Inscription'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        amount_cents: {
            anyOf: [
                {
                    type: 'integer',
                    exclusiveMinimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Amount Cents'
        },
        type: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/TransactionType'
                },
                {
                    type: 'null'
                }
            ]
        },
        note: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Note'
        },
        source_file: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Source File'
        },
        statement_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Statement Date'
        },
        category_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Category Id'
        }
    },
    type: 'object',
    title: 'TransactionUpdate'
} as const;

export const TransactionsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/TransactionPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'TransactionsPublic'
} as const;

export const UpdatePasswordSchema = {
    properties: {
        current_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Current Password'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['current_password', 'new_password'],
    title: 'UpdatePassword'
} as const;

export const UserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserCreate'
} as const;

export const UserPublicSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        }
    },
    type: 'object',
    required: ['email', 'id'],
    title: 'UserPublic'
} as const;

export const UserRegisterSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserRegister'
} as const;

export const UserUpdateSchema = {
    properties: {
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 128,
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        }
    },
    type: 'object',
    title: 'UserUpdate'
} as const;

export const UserUpdateMeSchema = {
    properties: {
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        }
    },
    type: 'object',
    title: 'UserUpdateMe'
} as const;

export const UsersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/UserPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'UsersPublic'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;