// This file is auto-generated by @hey-api/openapi-ts

export type AccountCreate = {
    name: string;
    type: AccountType;
    institution?: (string | null);
    description?: (string | null);
};

export type AccountPublic = {
    name: string;
    type: AccountType;
    institution?: (string | null);
    description?: (string | null);
    id: string;
    created_at: string;
};

/**
 * Spending summary for a single account.
 */
export type AccountSpending = {
    account_id: string;
    account_name: string;
    account_type: string;
    total_expense_cents: number;
    total_income_cents: number;
    net_cents: number;
    transaction_count: number;
};

export type AccountsPublic = {
    data: Array<AccountPublic>;
    count: number;
};

/**
 * Response for account summary analysis.
 */
export type AccountSummaryResponse = {
    accounts: Array<AccountSpending>;
    consolidated_expense_cents: number;
    consolidated_income_cents: number;
    consolidated_net_cents: number;
    total_transaction_count: number;
    period_start: (string | null);
    period_end: (string | null);
};

export type AccountType = 'credit_card' | 'chequing' | 'savings' | 'investment' | 'other';

export type AccountUpdate = {
    name?: (string | null);
    type?: (AccountType | null);
    institution?: (string | null);
    description?: (string | null);
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type CategoriesPublic = {
    data: Array<CategoryPublic>;
    count: number;
};

export type CategoryCreate = {
    name: string;
};

export type CategoryPublic = {
    name: string;
    id: string;
    created_at: string;
};

/**
 * Spending data for a single category.
 */
export type CategorySpending = {
    category_id: (string | null);
    category_name: (string | null);
    total_cents: number;
    percentage: number;
    transaction_count: number;
};

export type CategoryUpdate = {
    name?: (string | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ItemCreate = {
    title: string;
    description?: (string | null);
};

export type ItemPublic = {
    title: string;
    description?: (string | null);
    id: string;
    owner_id: string;
};

export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
};

export type Message = {
    message: string;
};

/**
 * Spending data for a single month.
 */
export type MonthlySpending = {
    year: number;
    month: number;
    total_cents: number;
    transaction_count: number;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

/**
 * Response for spending by category analysis.
 */
export type SpendingByCategoryResponse = {
    data: Array<CategorySpending>;
    total_spending_cents: number;
    period_start: (string | null);
    period_end: (string | null);
};

/**
 * Response for monthly spending trends.
 */
export type SpendingTrendsResponse = {
    data: Array<MonthlySpending>;
    total_spending_cents: number;
    period_start: (string | null);
    period_end: (string | null);
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type TransactionCreate = {
    date_transaction: string;
    date_inscription?: (string | null);
    description: string;
    amount_cents: number;
    type: TransactionType;
    note?: (string | null);
    source_file?: (string | null);
    statement_date?: (string | null);
    account_id: string;
    category_id?: (string | null);
};

export type TransactionPublic = {
    date_transaction: string;
    date_inscription?: (string | null);
    description: string;
    amount_cents: number;
    type: TransactionType;
    note?: (string | null);
    source_file?: (string | null);
    statement_date?: (string | null);
    id: string;
    account_id: string;
    category_id: (string | null);
    status: TransactionStatus;
    created_at: string;
    account: AccountPublic;
    category: (CategoryPublic | null);
};

export type TransactionsPublic = {
    data: Array<TransactionPublic>;
    count: number;
};

export type TransactionStatus = 'auto' | 'confirmed' | 'manual';

export type TransactionType = 'expense' | 'income' | 'transfer';

export type TransactionUpdate = {
    date_transaction?: (string | null);
    date_inscription?: (string | null);
    description?: (string | null);
    amount_cents?: (number | null);
    type?: (TransactionType | null);
    note?: (string | null);
    source_file?: (string | null);
    statement_date?: (string | null);
    category_id?: (string | null);
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type AccountsReadAccountsData = {
    limit?: number;
    skip?: number;
};

export type AccountsReadAccountsResponse = (AccountsPublic);

export type AccountsCreateAccountData = {
    requestBody: AccountCreate;
};

export type AccountsCreateAccountResponse = (AccountPublic);

export type AccountsReadAccountData = {
    id: string;
};

export type AccountsReadAccountResponse = (AccountPublic);

export type AccountsUpdateAccountData = {
    id: string;
    requestBody: AccountUpdate;
};

export type AccountsUpdateAccountResponse = (AccountPublic);

export type AccountsDeleteAccountData = {
    id: string;
};

export type AccountsDeleteAccountResponse = (Message);

export type AnalysisGetSpendingByCategoryData = {
    /**
     * Filter by specific account
     */
    accountId?: (string | null);
    /**
     * Start date for analysis (inclusive)
     */
    dateFrom?: (string | null);
    /**
     * End date for analysis (inclusive)
     */
    dateTo?: (string | null);
};

export type AnalysisGetSpendingByCategoryResponse = (SpendingByCategoryResponse);

export type AnalysisGetSpendingTrendsData = {
    /**
     * Filter by specific account
     */
    accountId?: (string | null);
    /**
     * Start date for analysis (inclusive)
     */
    dateFrom?: (string | null);
    /**
     * End date for analysis (inclusive)
     */
    dateTo?: (string | null);
};

export type AnalysisGetSpendingTrendsResponse = (SpendingTrendsResponse);

export type AnalysisGetAccountSummaryData = {
    /**
     * Start date for analysis (inclusive)
     */
    dateFrom?: (string | null);
    /**
     * End date for analysis (inclusive)
     */
    dateTo?: (string | null);
};

export type AnalysisGetAccountSummaryResponse = (AccountSummaryResponse);

export type CategoriesReadCategoriesData = {
    limit?: number;
    skip?: number;
};

export type CategoriesReadCategoriesResponse = (CategoriesPublic);

export type CategoriesCreateCategoryData = {
    requestBody: CategoryCreate;
};

export type CategoriesCreateCategoryResponse = (CategoryPublic);

export type CategoriesReadCategoryData = {
    id: string;
};

export type CategoriesReadCategoryResponse = (CategoryPublic);

export type CategoriesUpdateCategoryData = {
    id: string;
    requestBody: CategoryUpdate;
};

export type CategoriesUpdateCategoryResponse = (CategoryPublic);

export type CategoriesDeleteCategoryData = {
    id: string;
};

export type CategoriesDeleteCategoryResponse = (Message);

export type ItemsReadItemsData = {
    limit?: number;
    skip?: number;
};

export type ItemsReadItemsResponse = (ItemsPublic);

export type ItemsCreateItemData = {
    requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = (ItemPublic);

export type ItemsReadItemData = {
    id: string;
};

export type ItemsReadItemResponse = (ItemPublic);

export type ItemsUpdateItemData = {
    id: string;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = (ItemPublic);

export type ItemsDeleteItemData = {
    id: string;
};

export type ItemsDeleteItemResponse = (Message);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type TransactionsReadTransactionsData = {
    /**
     * Filter by account ID
     */
    accountId?: (string | null);
    /**
     * Filter by category ID (use 'uncategorized' for NULL)
     */
    categoryId?: (string | null);
    /**
     * Filter transactions to this date (inclusive)
     */
    endDate?: (string | null);
    limit?: number;
    skip?: number;
    /**
     * Filter transactions from this date (inclusive)
     */
    startDate?: (string | null);
    /**
     * Filter by transaction status
     */
    status?: (TransactionStatus | null);
};

export type TransactionsReadTransactionsResponse = (TransactionsPublic);

export type TransactionsCreateTransactionData = {
    requestBody: TransactionCreate;
};

export type TransactionsCreateTransactionResponse = (TransactionPublic);

export type TransactionsReadUncategorizedTransactionsData = {
    limit?: number;
    skip?: number;
};

export type TransactionsReadUncategorizedTransactionsResponse = (TransactionsPublic);

export type TransactionsReadPendingConfirmationTransactionsData = {
    limit?: number;
    skip?: number;
};

export type TransactionsReadPendingConfirmationTransactionsResponse = (TransactionsPublic);

export type TransactionsReadTransactionData = {
    id: string;
};

export type TransactionsReadTransactionResponse = (TransactionPublic);

export type TransactionsUpdateTransactionData = {
    id: string;
    requestBody: TransactionUpdate;
};

export type TransactionsUpdateTransactionResponse = (TransactionPublic);

export type TransactionsDeleteTransactionData = {
    id: string;
};

export type TransactionsDeleteTransactionResponse = (Message);

export type TransactionsCategorizeTransactionData = {
    categoryId: string;
    id: string;
};

export type TransactionsCategorizeTransactionResponse = (TransactionPublic);

export type TransactionsConfirmTransactionData = {
    id: string;
};

export type TransactionsConfirmTransactionResponse = (TransactionPublic);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);