// This file is auto-generated by @hey-api/openapi-ts

export type AccountCreate = {
    name: string;
    type: AccountType;
    institution?: (string | null);
    description?: (string | null);
};

export type AccountPublic = {
    name: string;
    type: AccountType;
    institution?: (string | null);
    description?: (string | null);
    id: string;
    owner_id: string;
    created_at: string;
};

export type AccountsPublic = {
    data: Array<AccountPublic>;
    count: number;
};

export type AccountType = 'credit_card' | 'chequing' | 'savings' | 'investment' | 'other';

export type AccountUpdate = {
    name?: (string | null);
    type?: (AccountType | null);
    institution?: (string | null);
    description?: (string | null);
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type CategoriesPublic = {
    data: Array<CategoryPublic>;
    count: number;
};

export type CategorizationRuleCreate = {
    rule_text: string;
    priority?: number;
    account_id?: (string | null);
    category_id: string;
};

export type CategorizationRulePublic = {
    rule_text: string;
    priority?: number;
    id: string;
    owner_id: string;
    account_id: (string | null);
    category_id: string;
    created_at: string;
};

export type CategorizationRulesPublic = {
    data: Array<CategorizationRulePublic>;
    count: number;
};

export type CategorizationRuleUpdate = {
    rule_text?: (string | null);
    priority?: (number | null);
    account_id?: (string | null);
    category_id?: (string | null);
};

export type CategoryCreate = {
    name: string;
};

export type CategoryPublic = {
    name: string;
    id: string;
    owner_id: string;
    created_at: string;
};

export type CategorySummary = {
    category_id: (string | null);
    category_name: (string | null);
    total_cents: number;
    transaction_count: number;
};

export type CategoryUpdate = {
    name?: (string | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type TransactionCreate = {
    date_transaction: string;
    date_inscription?: (string | null);
    description: string;
    amount_cents: number;
    type: TransactionType;
    note?: (string | null);
    source_file?: (string | null);
    statement_date?: (string | null);
    account_id: string;
    category_id?: (string | null);
    status?: TransactionStatus;
};

export type TransactionPublic = {
    date_transaction: string;
    date_inscription?: (string | null);
    description: string;
    amount_cents: number;
    type: TransactionType;
    note?: (string | null);
    source_file?: (string | null);
    statement_date?: (string | null);
    id: string;
    owner_id: string;
    account_id: string;
    category_id: (string | null);
    status: TransactionStatus;
    created_at: string;
};

export type TransactionsPublic = {
    data: Array<TransactionPublic>;
    count: number;
};

export type TransactionStatus = 'auto' | 'confirmed' | 'manual';

export type TransactionType = 'expense' | 'income' | 'transfer';

export type TransactionUpdate = {
    date_transaction?: (string | null);
    date_inscription?: (string | null);
    description?: (string | null);
    amount_cents?: (number | null);
    type?: (TransactionType | null);
    category_id?: (string | null);
    status?: (TransactionStatus | null);
    note?: (string | null);
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type AccountsReadAccountsData = {
    limit?: number;
    skip?: number;
};

export type AccountsReadAccountsResponse = (AccountsPublic);

export type AccountsCreateAccountData = {
    requestBody: AccountCreate;
};

export type AccountsCreateAccountResponse = (AccountPublic);

export type AccountsReadAccountData = {
    id: string;
};

export type AccountsReadAccountResponse = (AccountPublic);

export type AccountsUpdateAccountData = {
    id: string;
    requestBody: AccountUpdate;
};

export type AccountsUpdateAccountResponse = (AccountPublic);

export type AccountsDeleteAccountData = {
    id: string;
};

export type AccountsDeleteAccountResponse = (Message);

export type CategoriesReadCategoriesData = {
    limit?: number;
    skip?: number;
};

export type CategoriesReadCategoriesResponse = (CategoriesPublic);

export type CategoriesCreateCategoryData = {
    requestBody: CategoryCreate;
};

export type CategoriesCreateCategoryResponse = (CategoryPublic);

export type CategoriesReadCategoryData = {
    id: string;
};

export type CategoriesReadCategoryResponse = (CategoryPublic);

export type CategoriesUpdateCategoryData = {
    id: string;
    requestBody: CategoryUpdate;
};

export type CategoriesUpdateCategoryResponse = (CategoryPublic);

export type CategoriesDeleteCategoryData = {
    id: string;
};

export type CategoriesDeleteCategoryResponse = (Message);

export type CategorizationRulesReadRulesData = {
    accountId?: (string | null);
    limit?: number;
    skip?: number;
};

export type CategorizationRulesReadRulesResponse = (CategorizationRulesPublic);

export type CategorizationRulesCreateRuleData = {
    requestBody: CategorizationRuleCreate;
};

export type CategorizationRulesCreateRuleResponse = (CategorizationRulePublic);

export type CategorizationRulesReadRuleData = {
    id: string;
};

export type CategorizationRulesReadRuleResponse = (CategorizationRulePublic);

export type CategorizationRulesUpdateRuleData = {
    id: string;
    requestBody: CategorizationRuleUpdate;
};

export type CategorizationRulesUpdateRuleResponse = (CategorizationRulePublic);

export type CategorizationRulesDeleteRuleData = {
    id: string;
};

export type CategorizationRulesDeleteRuleResponse = (Message);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type TransactionsReadTransactionsData = {
    accountId?: (string | null);
    categoryId?: (string | null);
    endDate?: (string | null);
    limit?: number;
    skip?: number;
    startDate?: (string | null);
};

export type TransactionsReadTransactionsResponse = (TransactionsPublic);

export type TransactionsCreateTransactionData = {
    requestBody: TransactionCreate;
};

export type TransactionsCreateTransactionResponse = (TransactionPublic);

export type TransactionsGetTransactionsSummaryData = {
    accountId?: (string | null);
    endDate?: (string | null);
    startDate?: (string | null);
};

export type TransactionsGetTransactionsSummaryResponse = (Array<CategorySummary>);

export type TransactionsReadTransactionData = {
    id: string;
};

export type TransactionsReadTransactionResponse = (TransactionPublic);

export type TransactionsUpdateTransactionData = {
    id: string;
    requestBody: TransactionUpdate;
};

export type TransactionsUpdateTransactionResponse = (TransactionPublic);

export type TransactionsDeleteTransactionData = {
    id: string;
};

export type TransactionsDeleteTransactionResponse = (Message);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);