"""Add financial models: Account, Category, Transaction

Revision ID: 9a3d3d48f010
Revises: 1a31ce608336
Create Date: 2026-01-08 21:55:30.227674

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '9a3d3d48f010'
down_revision = '1a31ce608336'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('type', sa.Enum('CREDIT_CARD', 'CHEQUING', 'SAVINGS', 'INVESTMENT', 'OTHER', name='accounttype'), nullable=False),
    sa.Column('institution', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('category',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('transaction',
    sa.Column('date_transaction', sa.Date(), nullable=False),
    sa.Column('date_inscription', sa.Date(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('EXPENSE', 'INCOME', 'TRANSFER', name='transactiontype'), nullable=False),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('source_file', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('statement_date', sa.Date(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('AUTO', 'CONFIRMED', 'MANUAL', name='transactionstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('amount_cents > 0', name='positive_amount'),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'date_transaction', 'description', 'amount_cents', 'statement_date', name='unique_transaction')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction')
    op.drop_table('category')
    op.drop_table('account')
    # ### end Alembic commands ###
