"""Add ImportSession model

Revision ID: 9bba686d03a4
Revises: df7c67d9e31e
Create Date: 2026-01-16 04:07:48.557022

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '9bba686d03a4'
down_revision = 'df7c67d9e31e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('importsession',
    sa.Column('file_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'REJECTED', 'FAILED', name='importstatus'), nullable=False),
    sa.Column('transaction_count', sa.Integer(), nullable=False),
    sa.Column('statement_date', sa.Date(), nullable=True),
    sa.Column('statement_total_cents', sa.Integer(), nullable=True),
    sa.Column('calculated_total_cents', sa.Integer(), nullable=True),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('ix_unique_transaction_with_statement_date'), table_name='transaction', postgresql_where='(statement_date IS NOT NULL)')
    op.drop_index(op.f('ix_unique_transaction_without_statement_date'), table_name='transaction', postgresql_where='(statement_date IS NULL)')
    op.create_unique_constraint('unique_transaction', 'transaction', ['account_id', 'date_transaction', 'description', 'amount_cents', 'statement_date'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_transaction', 'transaction', type_='unique')
    op.create_index(op.f('ix_unique_transaction_without_statement_date'), 'transaction', ['account_id', 'date_transaction', 'description', 'amount_cents'], unique=True, postgresql_where='(statement_date IS NULL)')
    op.create_index(op.f('ix_unique_transaction_with_statement_date'), 'transaction', ['account_id', 'date_transaction', 'description', 'amount_cents', 'statement_date'], unique=True, postgresql_where='(statement_date IS NOT NULL)')
    op.drop_table('importsession')
    # ### end Alembic commands ###
